name: Deploy React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        # run: echo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      # run: npm install # for installin Node.js we can use npm ci 
      - name: Install dependencies
        run: pip install --upgrade pip #pip install # for Python installing
      - name: Test application # testing our application
        run: pip install pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        # run: echo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      # run: npm install # for installin Node.js we can use npm ci 
      - name: Install dependencies
        run: pip install --upgrade pip #pip install # for Python installing
      - name: Lint application Lint with Ruff # 
        run: black --check --diff
  build:
      runs-on: ubuntu-latest
      needs: lint
      steps:
      - name: Get repository code
        # run: echo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      # run: npm install # for installin Node.js we can use npm ci 
      - name: Install dependencies
        run: 
          pip install --upgrade pip git+https://github.com/pypa/build
          pip install build
          # pip install git+https://git+https://github.com/spdk/spdk.git#subdirectory=python/spdk
      - name: Build application # 
        run: 
          python -m sysconfig
          python3 -m build
      - name: Deploy
        run: echo Deploying... 
