name: Test React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        # run: echo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      # run: npm install # for installin Node.js we can use npm ci 
      - name: Install dependencies
        run: pip install --upgrade pip #pip install # for Python installing
      - name: Test application # testing our application
        run: pip install pytest
